stages:
- create-pipeline
- build-jobs

variables:
  CI_DEBUG_TRACE: "true"

default:
  before_script:
  - export BUILD_DATE=$(echo $CI_COMMIT_TIMESTAMP | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}') # Date format YYYY-MM-DD
  - export VERSION_ID=$(echo $CI_COMMIT_REF_NMAE)

create-pipeline:
  stage: create-pipeline
  script:
  - cat ci/default_*.yml > pipeline.yml
  - j2 templates/build_stages.yml.j2 data/spec.yml >> pipeline.yml
  - j2 templates/pipeline.yml.j2 data/spec.yml >> pipeline.yml
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
    - pipeline.yml
    expire_in: 10 min

build-jobs:
  stage: build-jobs
  trigger:
    include:
    - artifact: pipeline.yml
      job: create-pipeline
