# Thi is default 'before_script' for every job in pipeline
default:
  before_script:
  - export BUILD_DATE=$(echo $CI_COMMIT_TIMESTAMP | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}') # Date format YYYY-MM-DD
  - export VERSION_ID=$(echo $CI_COMMIT_REF_NAME)
  - echo "This is default 'before_script' for ALL jobs"
# This is variables for ALL jobs in pipeline
variables:
  MONGO_IMAGE: "mongo:5"
  POSTGRES_IMAGE: "postgres:15"
  PULL_POLICY: if_not_present
  COMPOSE_VERSION: "3.4"
# This is stages matrix. Cross of Modes and Types
stages:
- build-ha-thin
- build-ha-full
- build-standalone-thin
- build-standalone-full

product_one-basic-brand_one-ha-thin:
  stage: build-ha-thin
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_one
    BUNDLE: basic
    MODE: ha
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: thin
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-basic-brand_one-ha-thin"
  - scripts/build.sh
  rules:
  - when: manual

product_one-pro-brand_one-ha-thin:
  stage: build-ha-thin
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_one
    BUNDLE: pro
    MODE: ha
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: thin
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-pro-brand_one-ha-thin"
  - scripts/build.sh
  rules:
  - when: manual

product_one-ultimate-brand_one-ha-thin:
  stage: build-ha-thin
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_one
    BUNDLE: ultimate
    MODE: ha
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: thin
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-ultimate-brand_one-ha-thin"
  - scripts/build.sh
  rules:
  - when: on_success

product_one-basic-brand_two-ha-thin:
  stage: build-ha-thin
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_two
    BUNDLE: basic
    MODE: ha
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: thin
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-basic-brand_two-ha-thin"
  - scripts/build.sh
  rules:
  - when: manual

product_one-pro-brand_two-ha-thin:
  stage: build-ha-thin
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_two
    BUNDLE: pro
    MODE: ha
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: thin
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-pro-brand_two-ha-thin"
  - scripts/build.sh
  rules:
  - when: manual

product_one-ultimate-brand_two-ha-thin:
  stage: build-ha-thin
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_two
    BUNDLE: ultimate
    MODE: ha
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: thin
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-ultimate-brand_two-ha-thin"
  - scripts/build.sh
  rules:
  - when: on_success

product_two-ultimate-brand_one-ha-thin:
  stage: build-ha-thin
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_one
    BUNDLE: ultimate
    MODE: ha
    PRODUCT: product_two
    FRONT_TAG: 1.1-two
    TROUBLESHOOTING_ENABLE: "true"
    TYPE: thin
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_two-$VERSION_ID-$BUILD_DATE-ultimate-brand_one-ha-thin"
  - scripts/build.sh
  rules:
  - when: on_success

product_one-basic-brand_one-ha-full:
  stage: build-ha-full
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_one
    BUNDLE: basic
    MODE: ha
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: full
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-basic-brand_one-ha-full"
  - scripts/build.sh
  rules:
  - when: manual

product_one-pro-brand_one-ha-full:
  stage: build-ha-full
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_one
    BUNDLE: pro
    MODE: ha
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: full
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-pro-brand_one-ha-full"
  - scripts/build.sh
  rules:
  - when: never

product_one-ultimate-brand_one-ha-full:
  stage: build-ha-full
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_one
    BUNDLE: ultimate
    MODE: ha
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: full
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-ultimate-brand_one-ha-full"
  - scripts/build.sh
  rules:
  - when: on_success

product_one-basic-brand_two-ha-full:
  stage: build-ha-full
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_two
    BUNDLE: basic
    MODE: ha
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: full
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-basic-brand_two-ha-full"
  - scripts/build.sh
  rules:
  - when: manual

product_one-pro-brand_two-ha-full:
  stage: build-ha-full
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_two
    BUNDLE: pro
    MODE: ha
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: full
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-pro-brand_two-ha-full"
  - scripts/build.sh
  rules:
  - when: never

product_one-ultimate-brand_two-ha-full:
  stage: build-ha-full
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_two
    BUNDLE: ultimate
    MODE: ha
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: full
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-ultimate-brand_two-ha-full"
  - scripts/build.sh
  rules:
  - when: on_success

product_two-ultimate-brand_one-ha-full:
  stage: build-ha-full
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_one
    BUNDLE: ultimate
    MODE: ha
    PRODUCT: product_two
    FRONT_TAG: 1.1-two
    TROUBLESHOOTING_ENABLE: "true"
    TYPE: full
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_two-$VERSION_ID-$BUILD_DATE-ultimate-brand_one-ha-full"
  - scripts/build.sh
  rules:
  - when: on_success

product_one-basic-brand_one-standalone-thin:
  stage: build-standalone-thin
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_one
    BUNDLE: basic
    MODE: standalone
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: thin
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-basic-brand_one-standalone-thin"
  - scripts/build.sh
  rules:
  - when: manual

product_one-pro-brand_one-standalone-thin:
  stage: build-standalone-thin
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_one
    BUNDLE: pro
    MODE: standalone
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: thin
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-pro-brand_one-standalone-thin"
  - scripts/build.sh
  rules:
  - when: manual

product_one-ultimate-brand_one-standalone-thin:
  stage: build-standalone-thin
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_one
    BUNDLE: ultimate
    MODE: standalone
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: thin
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-ultimate-brand_one-standalone-thin"
  - scripts/build.sh
  rules:
  - when: on_success

product_one-basic-brand_two-standalone-thin:
  stage: build-standalone-thin
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_two
    BUNDLE: basic
    MODE: standalone
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: thin
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-basic-brand_two-standalone-thin"
  - scripts/build.sh
  rules:
  - when: manual

product_one-pro-brand_two-standalone-thin:
  stage: build-standalone-thin
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_two
    BUNDLE: pro
    MODE: standalone
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: thin
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-pro-brand_two-standalone-thin"
  - scripts/build.sh
  rules:
  - when: manual

product_one-ultimate-brand_two-standalone-thin:
  stage: build-standalone-thin
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_two
    BUNDLE: ultimate
    MODE: standalone
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: thin
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-ultimate-brand_two-standalone-thin"
  - scripts/build.sh
  rules:
  - when: on_success

product_two-ultimate-brand_one-standalone-thin:
  stage: build-standalone-thin
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_one
    BUNDLE: ultimate
    MODE: standalone
    PRODUCT: product_two
    FRONT_TAG: 1.1-two
    TROUBLESHOOTING_ENABLE: "true"
    TYPE: thin
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_two-$VERSION_ID-$BUILD_DATE-ultimate-brand_one-standalone-thin"
  - scripts/build.sh
  rules:
  - when: on_success

product_one-basic-brand_one-standalone-full:
  stage: build-standalone-full
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_one
    BUNDLE: basic
    MODE: standalone
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: full
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-basic-brand_one-standalone-full"
  - scripts/build.sh
  rules:
  - when: manual

product_one-pro-brand_one-standalone-full:
  stage: build-standalone-full
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_one
    BUNDLE: pro
    MODE: standalone
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: full
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-pro-brand_one-standalone-full"
  - scripts/build.sh
  rules:
  - when: never

product_one-ultimate-brand_one-standalone-full:
  stage: build-standalone-full
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_one
    BUNDLE: ultimate
    MODE: standalone
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: full
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-ultimate-brand_one-standalone-full"
  - scripts/build.sh
  rules:
  - when: manual

product_one-basic-brand_two-standalone-full:
  stage: build-standalone-full
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_two
    BUNDLE: basic
    MODE: standalone
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: full
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-basic-brand_two-standalone-full"
  - scripts/build.sh
  rules:
  - when: manual

product_one-pro-brand_two-standalone-full:
  stage: build-standalone-full
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_two
    BUNDLE: pro
    MODE: standalone
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: full
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-pro-brand_two-standalone-full"
  - scripts/build.sh
  rules:
  - when: never

product_one-ultimate-brand_two-standalone-full:
  stage: build-standalone-full
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_two
    BUNDLE: ultimate
    MODE: standalone
    PRODUCT: product_one
    FRONT_TAG: 1.0-one
    TROUBLESHOOTING_ENABLE: "false"
    TYPE: full
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_one-$VERSION_ID-$BUILD_DATE-ultimate-brand_two-standalone-full"
  - scripts/build.sh
  rules:
  - when: manual

product_two-ultimate-brand_one-standalone-full:
  stage: build-standalone-full
  allow_failure: true
  tags:
  - host
  variables:
    BRAND: brand_one
    BUNDLE: ultimate
    MODE: standalone
    PRODUCT: product_two
    FRONT_TAG: 1.1-two
    TROUBLESHOOTING_ENABLE: "true"
    TYPE: full
  script:
  - export PACKAGE_NAME="MY_PRODUCT-product_two-$VERSION_ID-$BUILD_DATE-ultimate-brand_one-standalone-full"
  - scripts/build.sh
  rules:
  - when: manual
